require:
  - rubocop-rails

AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.1
  DisplayCopNames: true
  Exclude:
    - "bin/*"
    - "vendor/**/*"

# Rails
Rails:
  Enabled: true
Rails/Blank:
  Enabled: true

# Style
Style/BlockDelimiters:
  Enabled: true
Style/EmptyLiteral:
  Enabled: true
Style/HashSyntax:
  Enabled: true
Style/MethodDefParentheses:
  Enabled: true
Style/Next:
  Enabled: true
Style/PercentLiteralDelimiters:
  Enabled: true
Style/StringLiterals:
  Enabled: true
Style/StringLiteralsInInterpolation:
  Enabled: true
Style/SymbolArray:
  Enabled: true
Style/TrailingCommaInHashLiteral:
  Enabled: true

# Layout
Layout/EmptyLines:
  Enabled: true
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/ExtraSpacing:
  Enabled: true
Layout/IndentationConsistency:
  Enabled: true
Layout/IndentationWidth:
  Enabled: true
Layout/LeadingCommentSpace:
  Enabled: true
Layout/SpaceAfterColon:
  Enabled: true
Layout/SpaceAfterComma:
  Enabled: true
Layout/SpaceAroundOperators:
  Enabled: true
Layout/SpaceBeforeBlockBraces:
  Enabled: true
Layout/SpaceInsideBlockBraces:
  Enabled: true
Layout/TrailingEmptyLines:
  Enabled: true
Layout/TrailingWhitespace:
  Enabled: true